### ISSUE TITLE
Must use proper import paths internally

### ISSUE THREAD

**Issue by niemeyer** [hanwen/go-enc2ly#1]
Glad to see this being done in Go.

There's a minor import path issue:

```
% go get github.com/hanwen/go-enc2ly     
package github.com/hanwen/go-enc2ly
        imports go-enc2ly/encore: unrecognized import path "go-enc2ly/encore"
package github.com/hanwen/go-enc2ly
        imports go-enc2ly/lily: unrecognized import path "go-enc2ly/lily"
```

The package should use "github.com/hanwen/go-enc2ly" internally as well.

**Comment by hanwen** [comment]
On Fri, Oct 5, 2012 at 3:07 PM, Gustavo Niemeyer
notifications@github.comwrote:

> Glad to see this being done in Go.
> 
> There's a minor import path issue:
> 
> please pull again.

## 

Han-Wen Nienhuys - hanwen@xs4all.nl - http://www.xs4all.nl/~hanwen
