### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by niemeyer** [hanwen/go-enc2ly#2]
Unfortunately it doesn't even build at the moment:

```
% go build
# github.com/hanwen/go-enc2ly
./analyze.go:136: d.Staff[0].VarData undefined (type *encore.Staff has no field or method VarData)
./analyze.go:142: c.VarData undefined (type *encore.Staff has no field or method VarData)
./analyze.go:144: c.VarData undefined (type *encore.Staff has no field or method VarData)
./analyze.go:154: c.VarData undefined (type *encore.Staff has no field or method VarData)
```

**Comment by hanwen** [comment]
Please try again.

On Fri, Oct 5, 2012 at 3:12 PM, Gustavo Niemeyer
notifications@github.comwrote:

> Unfortunately it doesn't even build at the moment:
> 
> % go build
> 
> # github.com/hanwen/go-enc2ly
> 
> ./analyze.go:136: d.Staff[0].VarData undefined (type *encore.Staff has no field or method VarData)
> ./analyze.go:142: c.VarData undefined (type *encore.Staff has no field or method VarData)
> ./analyze.go:144: c.VarData undefined (type *encore.Staff has no field or method VarData)
> ./analyze.go:154: c.VarData undefined (type *encore.Staff has no field or method VarData)
> 
>  —
> Reply to this email directly or view it on GitHubhttps://github.com/hanwen/go-enc2ly/issues/2.

## 

Han-Wen Nienhuys - hanwen@xs4all.nl - http://www.xs4all.nl/~hanwen
